#!/bin/sh
# vi: ts=2 sw=2

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly NC='\033[0m'

##################################################
#
# { PREVENT COMMIT TO THE MASTER BRANCH
# 
# https://stackoverflow.com/a/40465455/4276533
#
##################################################

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "${RED}You cannot commit directly to master branch$NC"
  exit 1
fi

##################################################
#
# } PREVENT COMMIT TO THE MASTER BRANCH
#
##################################################

##################################################
#
# { RUN SOME LOCAL TEST
#
##################################################

echo -n 'RUN PHP LINTER: '
./vendor/bin/php-cs-fixer fix src --dry-run --quiet
if [ $? -eq 0 ]; then
  echo "${GREEN}SUCCEEDED$NC"
else
  echo "${RED}FAILED$NC"
  echo 'Run `composer lint:php:fix` to fix the problem'\
      'and `git add` the change.'
  exit 1
fi

##################################################
#
# } RUN SOME LOCAL TEST
#
##################################################
